version: "3.9"

services:
  fika-server:
    image: ghcr.io/zhliau/fika-spt-server-docker:latest
    container_name: fika-server
    restart: unless-stopped
    ports:
      - 6969:6969
    environment:
      - UID=1000
      - GID=1000
      - INSTALL_FIKA=true
      - AUTO_UPDATE_SPT=true
      - AUTO_UPDATE_FIKA=true
      - TAKE_OWNERSHIP=true
      - ENABLE_PROFILE_BACKUPS=true
      - LISTEN_ALL_NETWORKS=true
    volumes:
      - ./server:/opt/server

  fika-headless:
    image: ghcr.io/svencodeflow/fikaheadlessclientamp:latest
    container_name: fika-headless
    depends_on:
      - fika-server
    environment:
      - DISPLAY=:0
    volumes:
      - ./client:/AMP/spt-fika-headless
