version: "3.9"

services:
  fika-headless:
    build: .
    container_name: fika-headless
    restart: unless-stopped
    ports:
      - "6969:6969"
    environment:
      # Diese ENV brauchst du nur, wenn das entrypoint.sh damit arbeitet
      - SERVER_URL=127.0.0.1
      - PORT=6969
      - PROFILE_ID=pmc
      # ...weitere Umgebungsvariablen je nach AMP-Konfig
    volumes:
      - ./tarkov:/tarkov
