version: "3.9"

services:
  fika-combined:
    build: .
    container_name: fika-combined
    restart: unless-stopped
    ports:
      - "6969:6969"
    environment:
      - UID=1000
      - GID=1000
      - INSTALL_FIKA=true
      - AUTO_UPDATE_SPT=true
      - AUTO_UPDATE_FIKA=true
      - TAKE_OWNERSHIP=true
      - ENABLE_PROFILE_BACKUPS=true
      - LISTEN_ALL_NETWORKS=true
      - NUM_HEADLESS_PROFILES=1
    volumes:
      - ./server:/opt/server
